FROM python:3.12-slim

WORKDIR /project

ENV PYTHONUNBUFFERED=1
ENV PYTHONDONTWRITEBYTECODE=1
ENV RAY_SERVE_HTTP_HOST="0.0.0.0"
ENV RAY_SERVE_HTTP_PORT="8000"

COPY requirements.txt .

RUN pip install --no-cache-dir -r requirements.txt

COPY app/ ./app
COPY models/ ./models
RUN mkdir -p /project/results
RUN mkdir -p /project/results/logs

EXPOSE 8000

CMD ["python", "app/server_ray.py"]