FROM python:3.12-slim

WORKDIR /project

ENV PYTHONUNBUFFERED=1
ENV PYTHONDONTWRITEBYTECODE=1
ENV RAY_SERVE_HTTP_HOST="0.0.0.0"
ENV RAY_SERVE_HTTP_PORT="8000"

COPY requirements.txt .

RUN pip install --no-cache-dir -r requirements.txt

COPY app/ ./app
COPY models/ ./models
RUN mkdir -p /project/results

EXPOSE 8000
EXPOSE 8265

CMD ["serve", "run", "app.server_ray:server_ray"]